// src/ui/Game.tsx
import { fetchMLBLive } from '@/lib/mlb'

export default function Game({ game }: { game: MLB.ScheduleGame }) {
	const { data, isLoading } = fetchMLBLive<MLB.LiveData>(game.link)

	if (isLoading) return <div>Loading...</div>

	if (!data) return <div>No data</div>

	const { detailedState } = data?.gameData.status
	const { liveData, gameData } = data
	const isActive = (
		[
			'In Progress',
			'Manager challenge',
			'Manager challenge: Tag play',
			'Umpire review',
		] as MLB.GameStatus['detailedState'][]
	).includes(detailedState)

	return (
		<div>
			<div className="flex gap-1">
				{gameData.teams.away.abbreviation}
				<b>{liveData.linescore.teams.away.runs}</b>
				vs
				<b>{liveData.linescore.teams.away.runs}</b>
				{gameData.teams.home.abbreviation}
				<span>({detailedState})</span>
				<span>
					{liveData.linescore.balls}-{liveData.linescore.strikes}
				</span>
			</div>

			{/* @ts-ignore */}
			{isActive && <marquee>{liveData.plays.currentPlay.result.description}</marquee>}
		</div>
	)
}

// src/ui/Game.svelte
<script lang="ts">
	import { fetchMLB, fetchMLBLive } from '@/lib/mlb'

	const { endpoint }: { endpoint: string } = $props()

	type DetailedState = MLB.GameStatus['detailedState']

	const isActive = (detailedState: DetailedState) =>
		(['In Progress', 'Manager challenge', 'Umpire review'] as DetailedState[]).includes(
			detailedState,
		)
</script>

{#await fetchMLBLive<MLB.LiveData>(endpoint)}
	<div>Loading game...</div>
{:then { gameData, liveData }}
	{@const { detailedState } = gameData.status}

	<div>
		{gameData.teams.away.abbreviation}
		{liveData.linescore.teams.away.runs} vs
		{liveData.linescore.teams.home.runs}
		{gameData.teams.home.abbreviation}
		({detailedState})

		{#if isActive(detailedState) && liveData.plays.currentPlay.result.description}
			<!-- svelte-ignore a11y_distracting_elements -->
			<marquee>
				{liveData.plays.currentPlay.result.description}
			</marquee>
		{/if}
	</div>

	<!-- {#if gameData.teams.home.abbreviation === 'LAD'}
		{$inspect(liveData)}
	{/if} -->
{/await}
